### PR TITLE
Tidy up - remove unused code

### PR DESCRIPTION
**Pull request by ramkumarkoppu**

### CODE REVIEW

**Review by chrism2671 — APPROVED** [review]

**Comment by chrism2671** [comment]
This commit has a conflict

**Comment by ramkumarkoppu** [comment]
what is the conflict?

**Comment by chrism2671** [comment]
No problem, I managed to fix it! :)

**Comment by ramkumarkoppu** [comment]
Cheers!

**Comment by ramkumarkoppu** [comment]
Do you know resource where I can see all possible good trend following
strategies? to experiment pytrendfollow with new stragegies?

**Comment by ramkumarkoppu** [comment]
IB native python API is available at http://interactivebrokers.github.io

**Pull request merged**
